const Tags = [
  "AI",
  "AR/VR",
  "Augmented Reality",
  "Automation",
  "Backend",
  "Big Data",
  "Blockchain",
  "Chatbots",
  "Cloud Computing",
  "Cloud Security",
  "Cybersecurity",
  "Data Science",
  "DevOps",
  "Digital Marketing",
  "E-commerce",
  "EdTech",
  "FinTech",
  "Frontend",
  "Full Stack",
  "Game Development",
  "Healthcare",
  "Hardware",
  "IoT",
  "Legal Tech",
  "Machine Learning",
  "Microservices",
  "Mobile",
  "NLP",
  "NFTs",
  "No-Code ",
  "Low-Code ",
  "PaaS",
  "Predictive Analytics",
  "Quantum Computing",
  "Robotics",
  "SaaS",
  "Software",
  "UX/UI Design",
  "Voice Assistants",
  "Virtual Reality",
  "Web",
];

const TechStackTags = [
  ".NET",
  "AI",
  "AWS",
  "Azure",
  "Backbone.js",
  "C",
  "C#",
  "C++",
  "CSS",
  "Dart",
  "Docker",
  "Django",
  "ElasticSearch",
  "Express.js",
  "Firebase",
  "Flask",
  "Git",
  "Go",
  "GraphQL",
  "HTML",
  "Hadoop",
  "Heroku",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Kafka",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Machine Learning",
  "MATLAB",
  "MongoDB",
  "MySQL",
  "Next.js",
  "Node.js",
  "NumPy",
  "OpenCV",
  "OpenGL",
  "Pandas",
  "PHP",
  "PostgreSQL",
  "Pytorch",
  "Python",
  "RabbitMQ",
  "React",
  "Redis",
  "Redux",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "SASS",
  "Scala",
  "Sequelize",
  "Spring",
  "SQL",
  "SQLite",
  "Svelte",
  "Swift",
  "TailwindCSS",
  "TensorFlow",
  "TypeScript",
  "Vue.js",
  "Webpack",
  "Xamarin",
];

const mockProjects = [
  {
    id: 1,
    name: "E-Learning Platform",
    title: "Interactive course creation platform",
    description:
      "Platform to create and share online courses with quizzes and video support.",
    domain: "Education",
    repoUrl: "https://github.com/example/ELearningPlatform",
    techStack: ["Django", "React.js", "PostgreSQL", "Redis"],
    tags: ["Education", "E-Learning", "Web"],
    contributorGuidelines:
      "Contributions should follow the existing coding style and include documentation for new features.",
    submittedBy: "Emily Clark",
    upvotes: 305,
  },
  {
    id: 2,
    name: "CollabMind",
    title: "Real-time collaboration platform",
    description:
      "Tool for teams to collaborate on documents, projects, and presentations with version control.",
    domain: "Web",
    repoUrl: "https://github.com/example/CollabMind",
    techStack: ["React.js", "Node.js", "WebSocket", "PostgreSQL"],
    tags: ["Collaboration", "Productivity", "Web"],
    contributorGuidelines:
      "Fork the repository, make changes in your local branch, and submit a PR. Include tests for new features.",
    submittedBy: "John Doe",
    upvotes: 215,
  },
  {
    id: 3,
    name: "DevOps Automation Tool",
    title: "Infrastructure automation tool",
    description:
      "Automates infrastructure deployment, monitoring, and scaling using a single configuration file.",
    domain: "Infrastructure",
    repoUrl: "https://github.com/example/DevOpsTool",
    techStack: ["Terraform", "Docker", "AWS", "Kubernetes"],
    tags: ["Automation", "DevOps", "Infrastructure"],
    contributorGuidelines:
      "Follow the contribution guidelines and ensure changes pass all CI/CD checks before submitting a PR.",
    submittedBy: "Jane Smith",
    upvotes: 320,
  },
  {
    id: 5,
    name: "Crypto Wallet",
    title: "Secure multi-asset cryptocurrency wallet",
    description:
      "Open-source wallet supporting multiple digital assets with enhanced security.",
    domain: "Blockchain",
    repoUrl: "https://github.com/example/CryptoWallet",
    techStack: ["React Native", "Solidity", "Ethereum", "Web3.js"],
    tags: ["Blockchain", "Cryptocurrency", "Mobile"],
    contributorGuidelines:
      "Submit PRs for security patches or feature enhancements. Ensure the wallet code complies with the latest security standards.",
    submittedBy: "Lucy Adams",
    upvotes: 145,
  },
];

const mockIdeas = [
  {
    id: 1,
    title: "Open Source Code Editor",
    description:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in incidunt",
    tags: ["Desktop", "Developer Tools"],
    features: ["Consequuntur est eos", "Consequuntur est eos"],
    likes: 156,
    comments: 23,
    collaborators: [
      {
        id: 1,
        name: "Alice Johnson",
        avatar: "/placeholder.svg?height=32&width=32",
        role: "Lead Developer",
      },
      {
        id: 2,
        name: "Bob Smith",
        avatar: "/placeholder.svg?height=32&width=32",
        role: "UX Designer",
      },
    ],
    suggestions: [
      {
        id: 1,
        user: "Charlie Brown",
        content: "Add support for multiple languages",
        votes: 15,
        timestamp: "2023-06-15T10:30:00Z",
      },
      {
        id: 2,
        user: "Diana Prince",
        content: "Implement a plugin system",
        votes: 12,
        timestamp: "2023-06-16T14:45:00Z",
      },
      {
        id: 3,
        user: "Ethan Hunt",
        content: "Create a dark mode theme",
        votes: 8,
        timestamp: "2023-06-17T09:15:00Z",
      },
      {
        id: 4,
        user: "Charlie Brown",
        content: "Add support for multiple languages",
        votes: 15,
        timestamp: "2023-06-15T10:30:00Z",
      },
      {
        id: 5,
        user: "Diana Prince",
        content: "Implement a plugin system",
        votes: 12,
        timestamp: "2023-06-16T14:45:00Z",
      },
      {
        id: 6,
        user: "Ethan Hunt",
        content: "Create a dark mode theme",
        votes: 8,
        timestamp: "2023-06-17T09:15:00Z",
      },
    ],
  },
  {
    id: 2,
    title: "AI-powered Task Manager",
    description:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in inciduntLorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in incidunt",
    features: [
      "Syntax highlighting for multiple programming languages",
      "Code auto-completion and suggestions",
      "Integrated terminal",
      "Git integration",
      "Customizable themes and extensions",
    ],
    tags: ["AI", "Mobile", "Productivity"],
    likes: 89,
    comments: 12,
    collaborators: [
      {
        id: 3,
        name: "Eve Williams",
        avatar: "/placeholder.svg?height=32&width=32",
        role: "AI Specialist",
      },
    ],
    suggestions: [
      {
        id: 4,
        user: "Frank Castle",
        content: "Integrate with popular calendar apps",
        votes: 8,
        timestamp: "2023-06-18T11:20:00Z",
      },
      {
        id: 5,
        user: "Grace Hopper",
        content: "Add voice command feature",
        votes: 6,
        timestamp: "2023-06-19T16:30:00Z",
      },
    ],
  },
  {
    id: 3,
    title: "Decentralized Social Media Platform",
    description:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in inciduntLorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in inciduntLorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in incidunt",
    features: [
      "Syntax highlighting for multiple programming languages",
      "Code auto-completion and suggestions",
      "Integrated terminal",
      "Git integration",
      "Customizable themes and extensions",
    ],
    tags: ["Web", "Blockchain", "Social"],
    likes: 201,
    comments: 34,
    collaborators: [
      {
        id: 4,
        name: "Grace Lee",
        avatar: "/placeholder.svg?height=32&width=32",
        role: "Blockchain Developer",
      },
      {
        id: 5,
        name: "Henry Ford",
        avatar: "/placeholder.svg?height=32&width=32",
        role: "Security Expert",
      },
    ],
    suggestions: [
      {
        id: 6,
        user: "Iris West",
        content: "Implement end-to-end encryption for messages",
        votes: 25,
        timestamp: "2023-06-20T13:10:00Z",
      },
      {
        id: 7,
        user: "Jack Sparrow",
        content: "Add a decentralized file sharing feature",
        votes: 18,
        timestamp: "2023-06-21T10:05:00Z",
      },
      {
        id: 8,
        user: "Kate Bishop",
        content: "Create a user-friendly wallet system",
        votes: 14,
        timestamp: "2023-06-22T15:40:00Z",
      },
    ],
  },
  {
    id: 4,
    title:
      "Open Source Code Editor Open Source Code Editor Open Source Code Editor",
    description:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in incidunt Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in incidunt Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, facere. Debitis hic aspernatur mollitia laboriosam optio qui quam voluptates quas tempora. Dolore neque in incidunt",
    features: ["Consequuntur est eos", "Consequuntur est eos"],
    tags: ["Desktop", "Developer Tools"],
    likes: 156,
    comments: 23,
    collaborators: [
      {
        id: 1,
        name: "Alice Johnson",
        avatar: "/placeholder.svg?height=32&width=32",
        role: "Lead Developer",
      },
      {
        id: 2,
        name: "Bob Smith",
        avatar: "/placeholder.svg?height=32&width=32",
        role: "UX Designer",
      },
    ],
    suggestions: [
      {
        id: 1,
        user: "Charlie Brown",
        content: "Add support for multiple languages",
        votes: 15,
        timestamp: "2023-06-15T10:30:00Z",
      },
      {
        id: 2,
        user: "Diana Prince",
        content: "Implement a plugin system",
        votes: 12,
        timestamp: "2023-06-16T14:45:00Z",
      },
      {
        id: 3,
        user: "Ethan Hunt",
        content: "Create a dark mode theme",
        votes: 8,
        timestamp: "2023-06-17T09:15:00Z",
      },
    ],
  },
];

TechStackTags.sort();

export { Tags, TechStackTags };
