const Tags = [
  "AI",
  "AR/VR",
  "Augmented Reality",
  "Automation",
  "Backend",
  "Big Data",
  "Blockchain",
  "Chatbots",
  "Cloud Computing",
  "Cloud Security",
  "Content Management Systems",
  "Cybersecurity",
  "Data Science",
  "DevOps",
  "Digital Marketing",
  "E-commerce",
  "Education Tech",
  "Fintech",
  "Frontend",
  "Full Stack",
  "Game Development",
  "Healthcare Tech",
  "Hardware",
  "IoT",
  "Legal Tech",
  "Machine Learning",
  "Microservices Architecture",
  "Mobile",
  "Natural Language Processing",
  "NFTs",
  "No-Code Development",
  "Low-Code Development",
  "PaaS",
  "Predictive Analytics",
  "Quantum Computing",
  "Robotics",
  "SaaS",
  "Software",
  "UX/UI Design",
  "Voice Assistants",
  "Virtual Reality",
  "Web",
];

const TechStackTags = [
  ".NET",
  "AI",
  "AWS",
  "Azure",
  "Backbone.js",
  "C",
  "C#",
  "C++",
  "CSS",
  "Dart",
  "Docker",
  "Django",
  "ElasticSearch",
  "Express.js",
  "Firebase",
  "Flask",
  "Git",
  "Go",
  "GraphQL",
  "HTML",
  "Hadoop",
  "Heroku",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Kafka",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Machine Learning",
  "MATLAB",
  "MongoDB",
  "MySQL",
  "Next.js",
  "Node.js",
  "NumPy",
  "OpenCV",
  "OpenGL",
  "Pandas",
  "PHP",
  "PostgreSQL",
  "Pytorch",
  "Python",
  "RabbitMQ",
  "React",
  "Redis",
  "Redux",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "SASS",
  "Scala",
  "Sequelize",
  "Spring",
  "SQL",
  "SQLite",
  "Svelte",
  "Swift",
  "TailwindCSS",
  "TensorFlow",
  "TypeScript",
  "Vue.js",
  "Webpack",
  "Xamarin",
];

TechStackTags.sort();

export { Tags, TechStackTags };
